// Estructura de datos compartida de bestias
// Agrega aquí tus bestias siguiendo el esquema indicado.
// Este archivo es consumido por index.html, detalle.html y filtros.html.
//
// {
//   nombre: "Nombre",
//   categoria: "Categoría 1|Categoría 2|Categoría 3|Categoría 4",
//   fortalezas: "Texto",
//   debilidades: "Texto",
//   dano_texto: "ej.: 1D6 + 1D4 (Mordisco venenoso)", // opcional
//   dano: 0, ca: 0, vitalidad: 0, px: 0,
//   movimiento: 0, dano_alcance: 0,
//   localizacion: "Texto",
//   alineamiento: "Texto",
//   descripcion: "Texto",
//   imagen: "ruta/a/imagen.png" // opcional
// }
//
// Nota: No se incluyen ejemplos adicionales para respetar tu petición.
// Categoria 1: de linea 24 hasta linea 755

window.bestias = [
  {
    nombre: "Serpopardo",
    categoria: "Categoría 1",
    fortalezas: "El serpopardo posee la misma agilidad y rapidez que un guepardo, lo que le permite moverse con destreza en terrenos variados y acechar a sus presas de manera efectiva. Se desplaza con gran sigilo, emitiendo un sonido similar al de una serpiente que proviene de todas las direcciones, lo que confunde a sus presas y dificulta su detección. Gracias a su lengua bípera y su aguda visión, el serpopardo puede percibir su entorno con gran precisión, detectando presas potenciales o peligros inminentes.",
    debilidades: "Aunque es ágil y rápido, el serpopardo se desenvuelve mejor en hábitats que le brinden cobertura y oportunidades para emboscar a sus presas. El humo puede ahuyentar al serpopardo, lo que dificulta su capacidad para cazar o moverse en áreas afectadas por incendios u otros tipos de humo. Las serpientes adicionales en su cuerpo pueden ser un punto vulnerable en combate cuerpo a cuerpo; un ataque dirigido adecuadamente a estas serpientes puede incapacitar temporalmente al serpopardo.",
    dano_texto: "1D6 + 1D4 (Mordisco venenoso)",
    dano: 6,
    ca: 8,
    vitalidad: 12,
    px: 750,
    movimiento: 8,
    dano_alcance: 1,
    localizacion: "Habita bosques o selvas donde puede camuflarse entre la vegetación y acechar a sus presas; también en áreas húmedas como pantanos o selvas tropicales.",
    alineamiento: "Neutral/Caótica",
    descripcion: "Criatura híbrida que combina aspectos de serpiente y guepardo. Presenta múltiples serpientes en lugar de una cola común, entrelazadas con el pelaje, otorgándole una apariencia única. Posee agilidad y velocidad comparables a felinos rápidos; su piel en el cuello se endurece formando una estructura similar a escamas; cabeza semejante a la de un guepardo, con orejas puntiagudas y ojos afilados. Lengua viperina para percibir el entorno con gran precisión.",
    imagen: "imgs/serpopardo.png"
  },
  {
    nombre: "Tauro",
    categoria: "Categoría 1",
    fortalezas: "Una vez que el Tauro realiza una embestida, se vuelve imparable, arrollando todo lo que tiene por delante gracias a su fuerza y constitución. Su capacidad de regeneración rápida le permite recuperarse de las heridas con rapidez, otorgándole una resistencia excepcional en batalla. Los cuernos del Tauro son armas letales que pueden perforar cualquier defensa, proporcionando ventaja significativa contra oponentes blindados.",
    debilidades: "No es un animal demasiado astuto y se deja guiar por su rabia incontrolable. Su regeneración rápida puede verse limitada por ciertos tipos de magia o ataques que afecten su capacidad de curación. Puede ser propenso a la fatiga debido a su tamaño masivo y al esfuerzo físico requerido en combates prolongados.",
    dano_texto: "2D8 (Embestida)",
    dano: 9,
    ca: 13,
    vitalidad: 28,
    px: 1500,
    movimiento: 9,
    dano_alcance: 1,
    localizacion: "En el plano terrenal, los Tauros suelen verse en las arenas de gladiadores, donde luchan contra oponentes experimentados en duelos a muerte. Estas criaturas imponentes son espectáculos populares en eventos de lucha de muchas culturas, donde se enfrentan a desafíos cada vez más difíciles para el deleite del público.",
    alineamiento: "Neutral/Caótica",
    descripcion: "El Tauro es una criatura imponente que se asemeja a un toro, pero con el doble de tamaño de un toro normal. Su cuerpo está cubierto por un pelaje oscuro y posee numerosas colas, lo que le otorga una apariencia intimidante. Sus heridas se regeneran con rapidez sorprendente, permitiéndole resistir incluso los ataques más feroces durante una lucha. Sus cuernos son extremadamente poderosos y capaces de perforar cualquier armadura o escudo convencional, convirtiéndolo en un oponente formidable en el campo de batalla.",
    imagen: "imgs/tauro.png"
  },
  {
    nombre: "Pez Khay",
    categoria: "Categoría 1",
    fortalezas: "Puede moverse sin restricciones entre distintos entornos, navegando por el plano abisal y otros medios como agua, aire, espacio, fuego, hielo o tierra. Posee la capacidad de revertir maldiciones y maleficios, actuando como agente de redención en el plano abisal. Al fusionarse con seres malditos, puede transmitir conocimientos almacenados en estos, aumentando la sabiduría y comprensión del plano abisal.",
    debilidades: "Es físicamente frágil y vulnerable a ataques directos; su pequeño tamaño lo convierte en presa fácil. No posee habilidades de combate y prefiere evitar el conflicto, quedando indefenso frente a amenazas directas. La magia infernal puede debilitarlo, comprometiendo su capacidad de redención; vulnerable en entornos altamente mágicos y hostiles.",
    dano_texto: "1D4 (Daño abisal)",
    ca: 17,
    vitalidad: 5,
    px: 100,
    movimiento: 7,
    dano_alcance: 1,
    localizacion: "Principalmente en el plano abisal, navegando libremente por cualquier lugar.",
    alineamiento: "Legal",
    descripcion: "Criatura singular del sombrío plano abisal. A primera vista puede confundirse con un pequeño delfín de apenas quince centímetros, pero su particularidad es moverse en cualquier tipo de medio: agua, aire, espacio, fuego, hielo o tierra. Su cuerpo muestra tonalidad blanca y gris con patrones de oleadas oscuras que recuerdan las profundidades abismales; una rareza entre las aberraciones y horrores del plano abisal.",
    imagen: "imgs/pezkhay.png"
  },
  {
    nombre: "Sanguijuela Enorme",
    categoria: "Categoría 1",
    fortalezas: "Sus enormes dimensiones le permiten dominar a presas pequeñas y ejercer presión abrumadora. Capacidad de ocultarse entre la vegetación acuática para emboscar efectivamente. Mandíbulas poderosas y dientes afilados capaces de infligir graves heridas y succionar grandes cantidades de sangre.",
    debilidades: "Puede ser torpe y lenta en tierra firme, volviéndose vulnerable a depredadores terrestres. Vulnerable a la deshidratación si se aleja del agua. Sus grandes ojos rojos son un punto débil; susceptibles a daños físicos o mágicos que afectan su capacidad de detectar presas y peligros.",
    dano_texto: "2D8 (Mordisco)",
    ca: 14,
    vitalidad: 74,
    px: 38850,
    movimiento: 6,
    dano_alcance: 3,
    localizacion: "Planos terrenales, especialmente pantanos; también cavernas subterráneas húmedas o sistemas de alcantarillado con suficiente humedad.",
    alineamiento: "Caótico",
    descripcion: "Criatura monstruosa semejante a una sanguijuela de hasta veinte metros de longitud. Habita en entornos acuáticos y pantanos, camuflándose entre la vegetación o enterrándose en el barro para acechar. Su cuerpo segmentado y piel resbaladiza le permiten adherirse firmemente a sus víctimas; mandíbulas equipadas con dientes afilados para perforar y succionar sangre. Destacan dos grandes ojos rojos que brillan en la oscuridad y varios ojos pequeños a lo largo de su cabeza.",
    imagen: "imgs/sanguijuelaenorme.png"
  },
  {
    nombre: "Stiarna",
    categoria: "Categoría 1",
    fortalezas: "Naturaleza dócil y gentil, ideal como montura o animal de transporte. Energía celestial en los cuernos que otorga protección y poder, mejorando la resistencia frente a ataques. Capacidad de iluminar el entorno con ojos azules incandescentes, útil para viajar o explorar en lugares oscuros o de noche.",
    debilidades: "Al ser dóciles no son agresivos ni se defienden en combate. Su protección disminuye en entornos con escasa bondad o energía celestial, volviéndose más vulnerables. Las temperaturas extremadamente calientes pueden afectarlos, reduciendo resistencia y capacidad para desempeñarse eficazmente.",
    dano_texto: "2D8 + 1D6 (cornada sagrada)",
    ca: 15,
    vitalidad: 28,
    px: 800,
    movimiento: 6,
    dano_alcance: 1,
    localizacion: "Oriundos del plano sagrado; también presentes en otros planos cuando son invocados o usados como monturas por seres benevolentes.",
    alineamiento: "Legal",
    descripcion: "Seres dóciles del plano sagrado, comúnmente monturas por su naturaleza tranquila. Apariencia similar a un ñu con pelaje grisáceo abundante que protege del frío y las inclemencias. Dos cuernos tipo reno portan energía celestial de poder y protección; ojos brillan con intenso azul incandescente capaz de iluminar el entorno. Llevan bolas de decoración y pelaje variado que añade belleza dulce.",
    imagen: "imgs/stiarna.png"
  },
  {
    nombre: "Unicornio",
    categoria: "Categoría 1",
    fortalezas: "Puede purificar árboles y lagos, restaurando vitalidad y equilibrio de ecosistemas. Lágrimas con propiedades curativas excepcionales. Gran agilidad y velocidad para evadir peligros; rapidez legendaria.",
    debilidades: "Emocionalmente frágil, susceptible a tristeza y depresión si es retenido contra su voluntad. La amputación del cuerno provoca muerte instantánea al ser su centro de poder y vitalidad. Receloso de la gente nueva y poco extrovertido, lo que dificulta formar alianzas.",
    dano_texto: "1D8 (Cornada)",
    ca: 8,
    vitalidad: 23,
    px: 650,
    movimiento: 11,
    dano_alcance: 1,
    localizacion: "Por norma general en el plano de ensueño; algunos encontrados perdidos en el plano terrenal.",
    alineamiento: "Legal",
    descripcion: "Bella criatura con apariencia de caballo y un único cuerno espiral en la frente capaz de purificar árboles y lagos. Profunda conexión con la naturaleza; esbelta y elegante, irradia pureza y nobleza. Emocionalmente frágil; retenerlo contra su voluntad puede llevarlo a la muerte por tristeza. Considerado de los animales terrestres más rápidos.",
    imagen: "imgs/unicornio.png"
  },
  {
    nombre: "Osoez",
    categoria: "Categoría 1",
    fortalezas: "Manipula sus espinas para adaptar defensa y ataque, obteniendo ventaja táctica. Depredador versátil con amplia dieta, capaz de sobrevivir en diversos entornos. Ataque a distancia lanzando espinas y regeneración inmediata.",
    debilidades: "Letargo prolongado lo vuelve vulnerable a la caza furtiva. La manipulación constante de las espinas puede agotarlo en combates largos. Sensible al frío, puede ralentizarse y volverse más letárgico.",
    dano_texto: "4D4 (Espina perforante)",
    ca: 8,
    vitalidad: 22,
    px: 1950,
    movimiento: 6,
    dano_alcance: 3,
    localizacion: "Diversas regiones del plano elemental, con entornos que favorecen su letargo y amplia variedad de alimentos.",
    alineamiento: "Neutral",
    descripcion: "Criatura corpulenta del tamaño de un oso con pelaje adornado por espinas similares a las de un erizo, distribuidas en espalda y extremidades. Puede modificar sus espinas haciéndolas más rígidas, flexibles, grandes o pequeñas según necesidad, brindando versatilidad defensiva y ofensiva. Conocido por su tendencia al letargo, activa mecanismos de defensa para evitar ser atacado; dieta extremadamente variada.",
    imagen: "imgs/osoez.png"
  },
  {
    nombre: "Pegaso",
    categoria: "Categoría 1",
    fortalezas: "Surca cielos con gran velocidad y destreza, evadiendo enemigos y explorando grandes extensiones. Musculatura poderosa y resistencia sorprendente para vuelos largos. Se dice que puede sanar a quienes toca su crin o beben aguas de los manantiales donde ha pisado.",
    debilidades: "Vulnerable a ataques mágicos que afectan el vuelo o la energía vital. Requiere espacios abiertos y cielos despejados; lugares confinados limitan su movilidad y debilitan su espíritu. Ser libre por naturaleza; capturarlo o someterlo puede provocar pérdida de gracia y sufrimiento emocional.",
    dano_texto: "2D6 (Golpe contundente)",
    ca: 9,
    vitalidad: 26,
    px: 950,
    movimiento: 9,
    dano_alcance: 1,
    localizacion: "Plano de ensueño; lugares remotos y vírgenes como praderas, bosques ancestrales o montañas inaccesibles.",
    alineamiento: "Legal",
    descripcion: "Majestuosa criatura que combina la gracia de un caballo con la libertad de un ave. Pelaje reluciente y poderosas alas blancas para volar con rapidez; crin y cola que fluyen como el viento; ojos de inteligencia y nobleza innatas. Irradia pureza y poder celestial; símbolo de esperanza y libertad.",
    imagen: "imgs/pegaso.png"
  },
  {
    nombre: "Ramidreju",
    categoria: "Categoría 1",
    fortalezas: "Encuentra cualquier tesoro sin importar su ocultación, gracias a su agudo sentido de ubicación. Pelaje con propiedades curativas que neutraliza alucinógenos y protege contra control mental. Excava galerías profundas para escapar o moverse bajo tierra con rapidez.",
    debilidades: "Muy pacífico; rara vez enfrenta enemigos y prefiere huir u ocultarse. Sólo encuentra tesoros o artefactos que se le han enseñado, limitando su uso sin guía. Fuerte sentido de comunidad; si se aísla o no se le atiende puede caer en depresión o autodestruirse.",
    dano_texto: "1D4 (Golpe)",
    ca: 16,
    vitalidad: 8,
    px: 250,
    movimiento: 6,
    dano_alcance: 1,
    localizacion: "Plano de ensueño; lugares apartados como bosques oscuros o montañas remotas donde puede excavar en paz.",
    alineamiento: "Neutral/Legal",
    descripcion: "Criatura extraordinaria que nace cada cien años; mezcla entre hurón y comadreja, más larga y ágil para moverse por galerías subterráneas. Pelaje con rayas verdes y negras; ojos amarillos intensos de apariencia mística. Famosa por excavar profundas galerías y por su pelaje con raras propiedades curativas. Puede localizar y traer cualquier tesoro que se le haya enseñado a encontrar; reacia a exponerse ante la sociedad.",
    imagen: "imgs/ramidreju.png"
  },
  {
    nombre: "Saetón",
    categoria: "Categoría 1",
    fortalezas: "Agilidad y rapidez en combate aéreo, capaz de esquivar bloqueos y sorprender desde distintos ángulos. Hipnotismo con la mirada que fascina o paraliza temporalmente. Puede transformar su cuerpo en diversas armas según la situación.",
    debilidades: "Vulnerable a magias elementales de hielo que ralentizan y afectan su agilidad. Tendencias suicidas que pueden llevarlo a actuar imprudentemente y poner en peligro a aliados. Atracción por el fuego, distrayéndolo del objetivo y exponiéndolo a riesgos adicionales.",
    dano_texto: "1D10",
    ca: 7,
    vitalidad: 8,
    px: 550,
    movimiento: 7,
    dano_alcance: 2,
    localizacion: "Plano terrenal; áreas boscosas y selváticas para camuflarse y acechar desde el aire; también zonas montañosas y ruinas antiguas.",
    alineamiento: "Neutral/Caótico",
    descripcion: "Serpiente larga y esbelta de oscuro color, capaz de serpentar por el aire con gracia y agilidad sorprendentes, lanzándose como una flecha contra enemigos. Ojos hipnóticos y fascinantes. Destaca su habilidad para modificar su cuerpo en una variedad de armas, otorgándole gran versatilidad táctica.",
    imagen: "imgs/saeton.png"
  },
  {
    nombre: "Myrmecoleón",
    categoria: "Categoría 1",
    fortalezas: "Combina fuerza de león con agilidad y resistencia de insecto, depredador formidable en el mundo subterráneo. Mandíbulas poderosas con toxina que permite triturar materiales y cazar presas con eficacia. Capacidad de volar limitada útil para moverse entre galerías y escapar de peligros.",
    debilidades: "Vulnerable a ataques coordinados por enemigos más grandes o mejor armados. Colonias susceptibles a invasión y destrucción por depredadores externos o conflictos internos. Débil ante magias elementales de agua o la tierra misma.",
    dano_texto: "1D6 + 1D6 (Mordisco + ácido)",
    ca: 11,
    vitalidad: 8,
    px: 300,
    movimiento: 4,
    dano_alcance: 1,
    localizacion: "Colonias subterráneas con intrincadas redes de túneles y cámaras para vivir y reproducirse.",
    alineamiento: "Neutral",
    descripcion: "Criatura única que fusiona características de león e insecto. Cabeza imponente con melena y mandíbulas poderosas; cuerpo con escamas metálicas doradas en torso y extremidades. Antenas de insecto desde la frente y alas similares a las de un escarabajo a lo largo de espalda y flancos; tamaño aproximado de 25 cm.",
    imagen: "imgs/myrmecoleon.png"
  },
  {
    nombre: "Nahual",
    categoria: "Categoría 1",
    fortalezas: "Transformación entre forma animal y humana brinda gran versatilidad según la situación. Instintos agudos y habilidades naturales útiles para cazar o rastrear. En forma humana aprovecha inteligencia y habilidades mágicas como manipulación de la naturaleza y conexión con espíritus animales.",
    debilidades: "Dualidad puede generar conflictos internos afectando decisiones y equilibrio emocional. Vulnerable a magia oscura, especialmente maldiciones o ataques espirituales. Hereda debilidades físicas asociadas a la especie animal representada.",
    dano_texto: "1D6 (Garras y colmillos)",
    ca: 9,
    vitalidad: 25,
    px: 1000,
    movimiento: 7,
    dano_alcance: 1,
    localizacion: "Diversos entornos naturales del plano terrenal, desde bosques frondosos hasta desiertos áridos.",
    alineamiento: "Neutral/Legal",
    descripcion: "Seres druídicos con dualidad única: forma animal con rasgos de su especie y forma humana más antropomórfica, conservando rasgos distintivos. Inteligencia, conexión con la naturaleza y habilidades mágicas les permiten adaptarse y enfrentarse a desafíos variados.",
    imagen: "imgs/nahual.png"
  },
  {
    nombre: "Nessie",
    categoria: "Categoría 1",
    fortalezas: "Piel escamosa y robusta ofrece defensa natural contra temperaturas extremas. Llama perpetua en la cola aporta calor constante y arma defensiva. Inmune al daño elemental de fuego al poder absorberlo con la cola.",
    debilidades: "El agua puede convertirse en debilidad en ciertos entornos, afectando su rendimiento. Hechizos o habilidades mágicas dirigidos en su contra impactan por su conexión elemental. Naturaleza pacífica puede ser explotada por quienes buscan causarle daño.",
    dano_texto: "1D4 (Mordisco)",
    ca: 18,
    vitalidad: 4,
    px: 100,
    movimiento: 6,
    dano_alcance: 1,
    localizacion: "Plano elemental; entornos afines a su naturaleza elemental.",
    alineamiento: "Neutral/Legal",
    descripcion: "Reptil pequeño semejante a dragones de Komodo pero con rostro más ancho. Cuerpo escamoso y robusto con ojos extremadamente oscuros, protuberancias óseas negras o anaranjadas y una llama perpetua encendida en la cola.",
    imagen: "imgs/nessie.png"
  },
  {
    nombre: "Nevul",
    categoria: "Categoría 1",
    fortalezas: "Invoca fuego corrupto y aliento de gas venenoso para infligir daño y debilitar enemigos. Habilidad de vuelo que aporta táctica y alcance desde el aire. Gran destreza para absorber magia nigromántica u oscura, obteniendo resistencia a esos ataques.",
    debilidades: "Vulnerable al fuego sagrado y la purificación que debilitan o neutralizan su poder corrupto. Alas susceptibles a daños físicos o mágicos, perdiendo eficacia si se deterioran durante el vuelo. Altamente engañoso con cualquiera que no sean sus amos.",
    dano_texto: "1D12 (Gas venenoso)",
    ca: 10,
    vitalidad: 17,
    px: 950,
    movimiento: 7,
    dano_alcance: 4,
    localizacion: "Áreas salvajes y deshabitadas; prefiere entornos oscuros y boscosos donde ocultarse y acechar.",
    alineamiento: "Caótico",
    descripcion: "Criatura con apariencia de cervatillo y alas de murciélago maldito adornadas con símbolos demoníacos. Cola de fuego corrupto y cuernos de alce largos y retorcidos; suele ser mascota de cazadores despiadados. Devora víctimas alimentándose de su energía vital.",
    imagen: "imgs/nevul.png"
  },
  {
    nombre: "Mengues",
    categoria: "Categoría 1",
    fortalezas: "Experto en ocultarse entre la vegetación para acechar sin ser detectado. Caza en grupo, abrumando a sus presas por número y devorándolas con rapidez. Sus cuerpos se utilizan en pócimas de control mental, valorados por quienes buscan manipular a otros.",
    debilidades: "Su diminuto tamaño los hace vulnerables a ser aplastados o eliminados si son descubiertos. Criaturas frágiles, fácilmente dañadas por ataques físicos o ciertas habilidades mágicas. Aversión natural al humo y sonidos muy estridentes, que pueden repelerlos o neutralizarlos.",
    dano_texto: "1D4 (Mordisco)",
    ca: 18,
    vitalidad: 2,
    px: 100,
    movimiento: 2,
    dano_alcance: 1,
    localizacion: "Plano terrenal; áreas boscosas y selváticas con alta concentración de bayas, helechos o frutos pequeños donde se refugian y se alimentan.",
    alineamiento: "Neutral/Caótico",
    descripcion: "Criaturas diminutas extremadamente peligrosas en manada, capaces de devorar a un humanoide de tamaño medio en segundos. Su capacidad de esconderse en la vegetación los convierte en amenaza sigilosa y mortal; sus cuerpos se emplean en la elaboración de pócimas de control mental.",
    imagen: "imgs/mengues.png"
  },
  {
    nombre: "Mondsichel",
    categoria: "Categoría 1",
    fortalezas: "Se mueven en grupos, coordinando defensa y ofensiva con esporas arcanas que debilitan y confunden enemigos. Invulnerables a la magia arcana, con gran resistencia frente a hechizos de ese tipo. Detectan aura mágica de objetos e identifican peligros o recursos mágicos en su entorno.",
    debilidades: "Físicamente frágiles y susceptibles a ataques físicos directos, especialmente cuando están solos. Su efectividad disminuye fuera de bosques ricos en energía arcana, volviéndose más vulnerables. Naturaleza amistosa y pacífica puede ser explotada por enemigos más agresivos.",
    dano_texto: "2D4 (Esporas arcanas)",
    ca: 10,
    vitalidad: 10,
    px: 150,
    movimiento: 8,
    dano_alcance: 1,
    localizacion: "Plano terrenal; se divisan en las noches de bosques encantados bajo la luz de la luna.",
    alineamiento: "Legal",
    descripcion: "Criaturas nocturnas parecidas a lémures con ojos brillantes y alas imbuidas de magia arcana. De pelaje plateado y azules oscuros, vuelan en armoniosas manadas liberando esporas que dejan rastro luminoso capaz de desorientar y debilitar enemigos.",
    imagen: "imgs/mondsichel.png"
  },
  {
    nombre: "Mono Volador",
    categoria: "Categoría 1",
    fortalezas: "Vuelo ágil con ventajas tácticas y exploratorias para acceder a áreas inaccesibles. Ecolocalización que aporta percepción adicional del entorno incluso con baja visibilidad. Extraordinariamente agresivos y obedientes a las órdenes de las brujas del páramo.",
    debilidades: "Relativamente frágiles y vulnerables a ataques físicos directos. Su lealtad puede ser manipulada en su contra ante influencias que contradigan las órdenes de las brujas. Estilo de lucha poco diestro, basado en fuerza bruta.",
    dano_texto: "2D6 (Mordisco)",
    ca: 10,
    vitalidad: 15,
    px: 300,
    movimiento: 6,
    dano_alcance: 1,
    localizacion: "Comunes en los páramos y refugios como castillos o fortalezas donde residen las brujas del páramo.",
    alineamiento: "Neutral/Caótico",
    descripcion: "Criaturas leales al servicio de las brujas del páramo, con apariencia que mezcla rasgos de babuino o chimpancé y alas membranosas de murciélago. Emplean ecolocalización para detectar objetos y criaturas en su ambiente.",
    imagen: "imgs/monovolador.png"
  },
  {
    nombre: "Musteradix",
    categoria: "Categoría 1",
    fortalezas: "Camuflaje natural eficaz, ocultándose en la vegetación del entorno. Gran agilidad en tierra y agua; puede comunicarse telepáticamente con su jinete para coordinar el transporte. Capacidad de encoger su tamaño y el de su jinete para adaptarse a distintas situaciones y escapar.",
    debilidades: "Dependencia del agua para su nutrición, vulnerable en zonas desérticas o con escasez hídrica. Vulnerable a la magia de fuego, sea elemental o infernal, que los debilita significativamente. Naturaleza vergonzosa o asustada al primer contacto, dificultando interacciones iniciales.",
    dano_texto: "2D6 + 1D4 (Garras + daño de naturaleza)",
    ca: 8,
    vitalidad: 18,
    px: 850,
    movimiento: 8,
    dano_alcance: 1,
    localizacion: "Tanto en el plano terrenal como en el de ensueño; principalmente en fuentes o estanques sagrados cercanos a bosques.",
    alineamiento: "Legal",
    descripcion: "Criaturas similares a nutrias compuestas de raíces y flora del lugar. Aproximadamente 75 cm de longitud, habitan fuentes o estanques sagrados próximos a encarnaciones de los bosques. Naturaleza pacífica; sirven como monturas para seres pequeños y destacan por agilidad y capacidad de escurrirse.",
    imagen: "imgs/musteradix.png"
  },
  {
    nombre: "Ninki Nanka",
    categoria: "Categoría 1",
    fortalezas: "Perfectamente adaptado a la vida en pantanos gracias a piel escamosa; se mueve con rapidez y sigilo a través de vegetación y fango. Resistencia notable a efectos de magia arcana, aportando ventaja contra hechiceros.",
    debilidades: "Físicamente más frágil que otros dragones por su tamaño reducido y ausencia de alas. Naturaleza asustada puede conducir a decisiones imprudentes. Particularmente vulnerable a magia elemental de rayo.",
    dano_texto: "2D6 + 1D4 (Garras dragón)",
    ca: 14,
    vitalidad: 23,
    px: 1150,
    movimiento: 4,
    dano_alcance: 1,
    localizacion: "Plano terrenal; exclusivamente en hábitats de pantanos, escondido entre vegetación densa y fango.",
    alineamiento: "Neutral",
    descripcion: "Criatura extraña de pantanos descrita como pequeño dragón del tamaño de un humanoide, sin alas y con cuerpo alargado de lagarto. Piel cubierta de escamas gruesas y resbaladizas adaptadas al entorno pantanoso; tonos verdes, marrones y grises para camuflarse.",
    imagen: "imgs/ninkinanka.png"
  },
  {
    nombre: "Lagatón",
    categoria: "Categoría 1",
    fortalezas: "Fuerza y agilidad felinas como montura robusta capaz de transportar a su jinete por terrenos difíciles, saltando y trepando. Adaptabilidad a distintos climas y entornos gracias a pelaje cálido y variado. Tras largo letargo en trampa mágica, desarrolló cierta resistencia a daños arcanos.",
    debilidades: "Vulnerable a cazadores furtivos que buscan su pelaje como trofeo. Propenso a reacciones violentas si se siente amenazado, riesgo para quien intenta domarlo o montarlo por primera vez. Limitaciones en entornos muy urbanizados u obstáculos que dificultan su agilidad.",
    dano_texto: "2D6 (Colmillos)",
    ca: 8,
    vitalidad: 23,
    px: 1350,
    movimiento: 7,
    dano_alcance: 1,
    localizacion: "Plano terrenal; áreas boscosas o montañosas donde encuentra refugio y caza; también en entornos urbanizados como montura domesticada.",
    alineamiento: "Neutral",
    descripcion: "Criatura similar a un dientes de sable de unos tres metros y varios cientos de kilos. De época arcaica de Terratea, quedó suspendida en una trampa mágica y ahora coexiste domesticada por aventureros que valoran su compañía y fuerza.",
    imagen: "imgs/lagaton.png"
  },
  {
    nombre: "Len Phale",
    categoria: "Categoría 1",
    fortalezas: "Pezuñas de cristal capaces de caminar sobre lava y roca magmática sin sufrir daño. Cuerpo de piedras preciosas y material cristalino que brinda camuflaje y protección subterránea. Cuerpo cristalino repele ciertos ataques mágicos inferiores, aumentando durabilidad.",
    debilidades: "Vulnerable a ataques físicos contundentes pese a su resistencia. Dieta especializada en gemas y roca magmática limita su supervivencia donde falten recursos. Susceptible a magia elemental de tierra y a influencias de roca magmática.",
    dano_texto: "1D8 (Proyectil elemental)",
    ca: 8,
    vitalidad: 19,
    px: 950,
    movimiento: 7,
    dano_alcance: 4,
    localizacion: "Plano terrenal y elemental; profundidades de cuevas subterráneas y territorios volcánicos geotérmicos con actividad magmática intensa.",
    alineamiento: "Neutral/Legal",
    descripcion: "Criatura similar a una alpaca pero de cristales y gemas. Pezuñas especiales absorben calor extremo. Se alimenta de gemas preciosas o roca magmática y se mezcla perfectamente con el entorno subterráneo.",
    imagen: "imgs/lenphale.png"
  },
  {
    nombre: "Lentorithox",
    categoria: "Categoría 1",
    fortalezas: "Piel segrega ácido altamente corrosivo que desintegra casi cualquier material, especialmente armas contundentes. Gruesa piel confiere resistencia a ataques físicos. Aunque lento, puede realizar embestidas o cargas sorpresivas aprovechando su masa para impactar con fuerza.",
    debilidades: "Falta de movilidad lo hace vulnerable a ataques rápidos y ágiles desde distancia. Vulnerable al fuego, que daña su piel pútrida y viscosa. Plata repele su ácido y puede causarle daño adicional debilitándolo en combate.",
    dano_texto: "1D6 (Embestida)",
    ca: 12,
    vitalidad: 5,
    px: 550,
    movimiento: 2,
    dano_alcance: 2,
    localizacion: "Bosques de Terratea; prefiere áreas donde moverse con relativa facilidad pese a su lentitud; amenaza para vida silvestre y viajeros desprevenidos.",
    alineamiento: "Neutral",
    descripcion: "Criatura grotesca con constitución de jabalí obeso. Piel viscosa y pútrida con olor acre; ácido tan corrosivo que desintegra lo que toca, incluida la mayoría de armas contundentes. Se camufla con el entorno.",
    imagen: "imgs/lentorithox.png"
  },
  {
    nombre: "Licinante",
    categoria: "Categoría 1",
    fortalezas: "Dominio notable sobre maldiciones y magia oscura, otorgando gran poder en el reino de la oscuridad. Cuerpo evolucionado con habilidades sobrenaturales para manipulación de magia negra. Conciencia propia desarrollada para decisiones estratégicas y tácticas con astucia.",
    debilidades: "Búsqueda constante de poder puede llevar a actos despiadados, volviéndolo enemigo temido. Vulnerable a purificación y luz, que contrarrestan sus habilidades oscuras. Carece de habilidades de combate cuerpo a cuerpo, debilitándolo en enfrentamientos físicos directos.",
    dano_texto: "1D8 (Maldición)",
    ca: 9,
    vitalidad: 9,
    px: 350,
    movimiento: 3,
    dano_alcance: 5,
    localizacion: "Rincones del plano terrenal donde magias oscuras o infernales han dejado su marca en el ambiente.",
    alineamiento: "Caótico",
    descripcion: "Criatura común que logró dominar maldiciones y magias oscuras notablemente. Su cuerpo experimentó evolución extraordinaria, adquiriendo características sobrenaturales y conciencia propia excepcional; ansia de poder lo impulsa a expandir su dominio.",
    imagen: "imgs/licinante.png"
  },
  {
    nombre: "Myethifagus",
    categoria: "Categoría 1",
    fortalezas: "Parásito espectral microscópico que cambia de huésped de manera indetectable. Aprende de las mentes que observa, imitando palabras y gestos con precisión. Una vez dentro del ojo de la víctima, puede poseer su mente y controlar su comportamiento.",
    debilidades: "Necesita un huésped para sobrevivir y continuar su ciclo. Si la cabeza del huésped se desintegra antes de saltar a otro huésped, puede ser destruido. Menor inteligencia o mayor caos del objetivo prolonga el tiempo de control, volviéndolo más vulnerable a ser detectado y eliminado.",
    dano_texto: "1D100 (Control mental)",
    ca: 9,
    vitalidad: 1,
    px: 500,
    movimiento: 1,
    dano_alcance: 10,
    localizacion: "Exclusivamente en el plano abisal.",
    alineamiento: "Neutral/Caótico",
    descripcion: "Parásito espectral que consume gradualmente el cerebro de su huésped, aprendiendo de las mentes y sincronizando acciones hasta anticipar movimientos y diálogos. Al dominar por completo, salta a la próxima víctima, controlando cuerpos sin cerebro temporalmente.",
    imagen: "imgs/myethifagus.png"
  },
  {
    nombre: "Grifo",
    categoria: "Categoría 1",
    fortalezas: "Posee una vista y audición excepcionales, lo que le permite detectar presas desde grandes distancias y reaccionar rápidamente ante cualquier amenaza. Puede atacar desde el aire con sus garras y pico afilados, o lanzarse al suelo con ferocidad para emboscar a sus presas terrestres. Puede surcar los cielos durante mucho tiempo sin descanso, patrullar grandes áreas y mantenerse fuera del alcance de muchos enemigos terrestres.",
    debilidades: "Vulnerable a los ataques a distancia, especialmente en pleno vuelo y expuesto a proyectiles o magias desde tierra. Requiere suficiente espacio para volar y maniobrar; en espacios cerrados o confinados su movilidad y efectividad se reducen. Vulnerable a la magia elemental de frío, que puede ralentizar su vuelo y disminuir su agilidad.",
    dano_texto: "2D6 (Garras)",
    ca: 10,
    vitalidad: 26,
    px: 1950,
    movimiento: 9,
    dano_alcance: 1,
    localizacion: "En el plano terrenal, habita lugares remotos y montañosos, encontrando refugio en acantilados y picos elevados.",
    alineamiento: "Neutral/Legal",
    descripcion: "Criatura legendaria que combina las características del majestuoso águila y un esbelto felino. Parte frontal de águila gigante con pico afilado, ojos penetrantes y garras poderosas; alas enormes que le permiten surcar los cielos. Parte posterior de felino musculoso cubierto de plumaje; patas robustas y ágiles adaptadas a la carrera y al salto; cola larga adornada con plumas de colores vivos.",
    imagen: "imgs/grifo.png"
  },
  {
    nombre: "Gružňa",
    categoria: "Categoría 1",
    fortalezas: "Velocidad y agilidad en el terreno que la convierten en medio de transporte rápido y eficiente. Camina por cualquier tipo de terreno manteniendo perfecta estabilidad, ideal para superficies irregulares o difíciles. Los cambios climáticos no la afectan y se mueve con facilidad bajo lluvia, nieve o sol.",
    debilidades: "No es beligerante y tiende a evitar el conflicto directo. Frágil ante combates físicos directos y puede resultar fácilmente herida en confrontaciones. Dependiente de sus amos y susceptible a sus decisiones o habilidades.",
    dano_texto: "1D8 (Picotazo)",
    ca: 9,
    vitalidad: 13,
    px: 1450,
    movimiento: 9,
    dano_alcance: 1,
    localizacion: "Reside en el plano elemental, en grandes grupos o como montura de habitantes de ese reino.",
    alineamiento: "Legal",
    descripcion: "Grulla de gran tamaño del plano elemental, distinguida por su amabilidad y utilidad como montura. Plumaje denso y elegante de tonalidades variadas según la región. Alas amplias y resistentes; no vuela, pero planea con soltura.",
    imagen: "imgs/gruzña.png"
  },
  {
    nombre: "Guang Gou",
    categoria: "Categoría 1",
    fortalezas: "Guardianes del templo de jade, expertos en meditación; ayudan a despejar la mente y alcanzar la paz interior. Emiten un aura sagrada que calma corazones inquietos y disipa energías negativas. Bloquean pensamientos dañinos o nocivos, liberando a las personas de influencias que perturban su paz.",
    debilidades: "Sensibles a emociones humanas, vulnerables a tristeza y angustia del entorno. Su afecto por corazones puros puede volverlos reservados o agresivos ante individuos con intenciones oscuras. Débiles ante la magia arcana, que los afecta y rehúyen.",
    dano_texto: "2D4 (mordisco sagrado)",
    ca: 9,
    vitalidad: 15,
    px: 1000,
    movimiento: 5,
    dano_alcance: 1,
    localizacion: "Principalmente en el plano sagrado; pequeño grupo en el plano terrenal, en el recinto del Templo de Jade.",
    alineamiento: "Legal",
    descripcion: "Criaturas caninas semejantes a perros divinos, de pelaje blanco reluciente con destellos dorados. Ojos profundos y serenos; presencia tranquila pero imponente, postura erguida y expresión serena que inspira respeto y calma.",
    imagen: "imgs/guanggou.png"
  },
  {
    nombre: "Kelpie",
    categoria: "Categoría 1",
    fortalezas: "Extremadamente ágiles y veloces en el agua, con gran ventaja táctica en su entorno. Capaces de detectar el alineamiento moral de las personas que encuentran, evaluando rápidamente intenciones y carácter. Altamente engañosos; incitan a víctimas a subir a sus lomos para llevarlas a profundidades y ahogarlas.",
    debilidades: "Vulnerables a ataques físicos y mágicos, especialmente a la magia elemental de rayo. Fuera del agua pierden agilidad y velocidad, volviéndose más vulnerables. Naturaleza caprichosa que puede llevarlos a subestimar oponentes y caer en trampas y estrategias bien planificadas.",
    dano_texto: "2D6 (Mordisco)",
    ca: 12,
    vitalidad: 20,
    px: 1400,
    movimiento: 9,
    dano_alcance: 1,
    localizacion: "Cuerpos de agua como lagos, ríos y mares; especialmente en áreas del plano terrenal y de ensueño donde la magia es más fuerte.",
    alineamiento: "Neutral/Caótico",
    descripcion: "Seres misteriosos con apariencia de caballo y cola de sirena. Cuerpos musculosos y crines largas; cola con escamas brillantes y membranas. Mirada penetrante y aura mágica; naturaleza caprichosa e impredecible que alterna entre ayudar y llevar a náufragos a su perdición bajo las profundidades.",
    imagen: "imgs/kelpie.png"
  },
  {
    nombre: "Gran Mosquito",
    categoria: "Categoría 1",
    fortalezas: "La probóscide puede perforar prácticamente cualquier cosa, atacando incluso objetivos protegidos por armaduras o estructuras resistentes. Inocula un veneno especial con su picadura que induce alucinaciones, agresividad extrema y puede causar la muerte; desorienta y debilita gravemente a oponentes. Posee velocidad extraordinaria para esquivar ataques y escapar rápidamente; se acerca y se retira con gran eficacia.",
    debilidades: "Físicamente frágil; si es alcanzado puede ser derrotado con relativa facilidad y un solo golpe bien dirigido. Tamaño relativamente grande lo hace más vulnerable y un blanco más fácil a distancia. La magia de frío o hielo puede ralentizarlo, reduciendo su velocidad y capacidad para esquivar.",
    dano_texto: "1D4 (Picadura)",
    ca: 13,
    vitalidad: 10,
    px: 150,
    movimiento: 7,
    dano_alcance: 1,
    localizacion: "Plano terrenal: áreas pantanosas, junglas densas y lugares húmedos con abundancia de sangre para alimentarse.",
    alineamiento: "Neutral/Caótico",
    descripcion: "Criatura insectoide de gran tamaño, con envergadura de hasta 30 cm. Probóscide o aguijón taladro capaz de perforar con precisión; a pesar de apariencia frágil, su agilidad y velocidad lo convierten en depredador temible.",
    imagen: "imgs/granmosquito.png"
  },
  {
    nombre: "Drakothor",
    categoria: "Categoría 1",
    fortalezas: "Piel escamosa con resistencia natural a ciertos tipos de magia, reduciendo daño de ataques mágicos, especialmente magia arcana. Múltiples ojos fluorescentes le permiten ver en la oscuridad, otorgando ventaja en lugares poco iluminados. Capacidad limitada de regeneración al estar en contacto con hongos o esporas del entorno, recuperando vitalidad paulatinamente en áreas fúngicas.",
    debilidades: "Piel especialmente susceptible al fuego, recibiendo el doble de daño de ataques de fuego. La exposición prolongada a la luz solar debilita su vitalidad, reduciéndola casi a la mitad bajo el sol. Sin esporas u hongos presentes, pierde su regeneración y su mordisco deja de transmitir esporas.",
    dano_texto: "1D10 (Mordisco) + 1D4 (Esporas)",
    ca: 13,
    vitalidad: 22,
    px: 1650,
    movimiento: 6,
    dano_alcance: 1,
    localizacion: "Plano terrenal; subsuelo. Protege territorios de micónidos y fúngicos, resguardando entradas y patrullando túneles y cavernas.",
    alineamiento: "Neutral",
    descripcion: "Conocido como los Guardianes de las Cavernas. Criatura formidable con cuerpo similar a cánido pero piel escamosa de reptil y múltiples ojos fluorescentes que brillan en la oscuridad. Protector de fortalezas fúngicas; su mordisco transmite esporas que germinan en el enemigo.",
    imagen: "imgs/drakothor.png"
  },
  {
    nombre: "Ferociraya",
    categoria: "Categoría 1",
    fortalezas: "Poderosas mandíbulas y fuerza impresionante; depredador capaz de enfrentarse a criaturas formidables. Pelaje resistente que ofrece protección frente a ataques físicos y condiciones ambientales adversas. Ágil y veloz pese a su tamaño, capaz de sorprender y esquivar ataques.",
    debilidades: "Instinto salvaje dificulta su control en situaciones estresantes o caóticas. Requiere jinete con carácter fuerte; puede actuar de forma errática o volverse contra aliados si no siente determinación. Vulnerable a ataques mágicos y aéreos desde diferentes ángulos.",
    dano_texto: "1D12 (Mordisco)",
    ca: 8,
    vitalidad: 16,
    px: 485,
    movimiento: 8,
    dano_alcance: 1,
    localizacion: "Plano terrenal: estepas, desiertos, páramos y sitios con poca vegetación; prefiere entornos abiertos para caza y combate.",
    alineamiento: "Neutral/Caótico",
    descripcion: "Imponente criatura que fusiona apariencia de cebra con ferocidad de león. Pelaje grueso y duro marcado por rayas; mandíbula con colmillos afilados y musculatura poderosa. Aura feroz que inspira respeto y temor.",
    imagen: "imgs/ferociraya.png"
  },
  {
    nombre: "Fognight",
    categoria: "Categoría 1",
    fortalezas: "Exhala niebla desde boca y fosas nasales, cubriendo el terreno para desplazarse y confundir enemigos. Capacidad de teletransportarse a través de la niebla, moviéndose rápidamente y apareciendo en diferentes lugares; oponente esquivo y difícil de atrapar. Sólo permite ser montado por jinetes de gran astucia; vínculo selectivo y especial.",
    debilidades: "Vulnerable a ataques físicos directos, especialmente si no puede crear niebla. Privado de su niebla, pierde movilidad y capacidades tácticas, limitando su efectividad. Carácter misterioso que dificulta su control en situaciones caóticas o estresantes; puede abandonar al jinete en momentos críticos.",
    dano_texto: "2D6 (Cornada embestida)",
    ca: 9,
    vitalidad: 20,
    px: 565,
    movimiento: 8,
    dano_alcance: 1,
    localizacion: "Plano terrenal; noches y lugares con niebla densa. Quienes lo encuentran pueden interactuar con él y montarlo si son astutos y dignos.",
    alineamiento: "Neutral",
    descripcion: "Criatura misteriosa de aspecto majestuoso semejante a un ciervo de gran estatura con complexión robusta como un caballo. Pezuñas similares a las de una cabra y cuernos extremadamente largos; pelaje de tonos claros que le permite camuflarse.",
    imagen: "imgs/fognight.png"
  },
  {
    nombre: "Fúngico",
    categoria: "Categoría 1",
    fortalezas: "Comunicación telepática que coordina actividades y comparte información en su comunidad, aportando ventaja en supervivencia y caza. Resplandor bioluminiscente útil como camuflaje o señalización en entornos oscuros, evitando depredadores y facilitando comunicación. Esparcen esporas con amplia gama de efectos, desde inducir sueño hasta causar envenenamiento mortal y rápido.",
    debilidades: "Sensibles a la luz solar directa; pueden sufrir daños por exposiciones prolongadas. Físicamente frágiles frente a otras razas; vulnerables a ataques físicos directos. Al habitar el mundo subterráneo, susceptibles a enfermedades y parásitos provenientes de la superficie.",
    dano_texto: "2D6 + 1D4 (Golpe venenoso)",
    ca: 13,
    vitalidad: 20,
    px: 600,
    movimiento: 5,
    dano_alcance: 2,
    localizacion: "Entornos subterráneos del mundo terrenal, donde prosperan por abundancia de materia orgánica y humedad.",
    alineamiento: "Neutral",
    descripcion: "Especie de setas antropomórficas de variados tamaños, colores y tipos de piel. Emiten suave bioluminiscencia, especialmente en la oscuridad. Se comunican telepáticamente entre ellos y con otras formas de vida; habitan zonas subterráneas.",
    imagen: "imgs/fungico.png"
  },
  {
    nombre: "Hipogrifo",
    categoria: "Categoría 1",
    fortalezas: "Vuela con gran rapidez y agilidad gracias a sus poderosas alas; ventaja para caza y evasión. En tierra, corredor veloz y resistente capaz de cubrir grandes distancias; depredador formidable. Puede pasar largos periodos sin alimentarse; prácticamente infatigable, mantiene actividad sin necesidad de descansar.",
    debilidades: "Vulnerable a ataques a distancia en pleno vuelo por proyectiles o magias desde tierra. Requiere espacio para volar y maniobrar; en entornos cerrados disminuye eficacia y capacidad de escapar. Salvaje y orgulloso; rechaza cautiverio y domesticación, dificultando entrenamiento y manejo como montura.",
    dano_texto: "3D4 (Picotazo)",
    ca: 12,
    vitalidad: 22,
    px: 1350,
    movimiento: 9,
    dano_alcance: 1,
    localizacion: "Plano terrenal; lugares remotos y montañosos, acantilados y picos elevados; también áreas boscosas y cercanías de cuevas o gargantas profundas.",
    alineamiento: "Neutral/Legal",
    descripcion: "Criatura legendaria que combina caballo y águila. Parte delantera de águila gigante con pico afilado, alas poderosas y garras robustas; parte posterior de caballo con cuerpo musculoso, patas robustas y cola larga. Alas grandes le permiten volar con gracia y rapidez.",
    imagen: "imgs/hipogrifo.png"
  },
  {
    nombre: "Cría de Dragón",
    categoria: "Categoría 1",
    fortalezas: "-Las crías de dragón poseen un potencial ilimitado de crecimiento y desarrollo, lo que les permite alcanzar la magnificiencia y poder de los dragones adultos con el tiempo.\n-Aunque sus habilidades mágicas pueden ser menos desarrolladas que las de los dragones adultos, aún pueden manifestar una variedad de habilidades mágicas y elementales, como el aliento de fuego, la manipulación del clima y varios más.\n-A pesar de su juventud, son resistentes y difíciles de derrotar. Sus cuerpos robustos y escamas protectoras les otorgan gran resistencia a ataques físicos y arcanos.",
    debilidades: "-Durante su desarrollo, pueden ser más vulnerables a amenazas externas debido a su menor tamaño y experiencia.\n-A medida que aprenden a dominar sus habilidades, pueden carecer de la experiencia y sabiduría necesarias para enfrentar desafíos complejos o estratégicos.\n-Son especialmente vulnerables a la magia elemental de rayo, que puede penetrar sus escamas protectoras y causar daño significativo.",
    dano_texto: "1D6 (Aliento de Dragón)",
    dano: 1, 
    ca: 16, 
    vitalidad: 25, 
    px: 1000,
    movimiento: 4,
    dano_alcance: 2,
    localizacion: "Pueden habitar el plano elemental o el plano terrenal, en el norte más profundo de Stungerb.",
    alineamiento: "Neutral/Caótico (puede variar según la influencia de sus padres y el entorno en el que son criados)",
    descripcion: "Las crías de dragón son versiones jóvenes de los legendarios dragones. Aunque varían según la especie, comparten rasgos comunes: cuerpos robustos, escamas relucientes y una apariencia más vivaz. A pesar de su juventud son seres muy peligrosos, con capacidad para habilidades mágicas y gran resistencia gracias a sus escamas protectoras.",
    imagen: "imgs/criadedragon.png"
  },
  {
    nombre: "Cusith",
    categoria: "Categoría 1",
    fortalezas: "-El Cusith puede crear un puente arco iris entre el plano terrenal y el plano de ensueño, permitiéndole viajar entre ambos mundos y transportar a otros.\n-Aunque es imponente en apariencia, el Cusith es una criatura pacífica y gentil que busca la armonía y prefiere evitar conflictos.\n-Sus alas astrales le proporcionan una capacidad de vuelo extraordinaria, permitiéndole desplazarse con gracia y velocidad a través de los cielos.",
    debilidades: "-El Cusith puede ser vulnerable a los poderes de corrupción oscura, que pueden debilitarlo o incluso controlar su voluntad.\n-Su naturaleza gentil y confiada puede llevarlo a confiar en aquellos que no lo merecen, exponiéndolo a situaciones de peligro o traición.\n-Los cuernos del Cusith son un punto débil; si se dañan, puede quedar indefenso.",
    dano_texto: "2D4 (Envestida)",
    dano: 2,
    ca: 8,
    vitalidad: 18,
    px: 900,
    movimiento: 8,
    dano_alcance: 1,
    localizacion: "El Cusith se encuentra generalmente en los días de lluvia soleada, cabalgando en el arco iris entre el plano terrenal y el plano de ensueño.",
    alineamiento: "Legal",
    descripcion: "El Cusith es una criatura mística conocida como la bestia que cabalga en el arco iris. Tiene cuerpo peludo de alce, cuernos majestuosos de gran ciervo, rostro sabio y gentil, y alas astrales de colores vivos semejantes al arco iris. Irradia calma y serenidad, transmitiendo una gentileza ancestral.",
    imagen: "imgs/cusith.png"
  },
  {
    "nombre": "Gramenbys",
    "categoria": "Categoría 1",
    "fortalezas": "Resistencia sobrenatural debido a su cuerpo de piedra mágica y viva, que les proporciona una protección excepcional contra ataques físicos y magia elemental.\nInfatigables, lo que les permite mantenerse en pie y combatir durante largos períodos sin mostrar signos de fatiga.\nDominio de la magia de la naturaleza, que les permite controlar las plantas, comunicarse con la vegetación y utilizar diversas habilidades mágicas relacionadas con la flora.",
    "debilidades": "Vulnerabilidad a la magia oscura o corrupta, que puede debilitar su conexión con la energía natural y sagrada, afectando su resistencia y habilidades.\nAunque su cuerpo de piedra es resistente, pueden ser vulnerables a ciertos tipos de ataques mágicos específicos que afecten directamente a los materiales minerales.\nSon más susceptibles a los ataques perforantes, ya que su resistencia se basa en gran medida en su dureza y protección superficial.",
    "dano_texto": "2D4 (arañazo)",
    "dano": 0,
    "ca": 7,
    "vitalidad": 20,
    "px": 10700,
    "movimiento": 8,
    "dano_alcance": 1,
    "localizacion": "En el plano terrenal, los Gramenbys suelen encontrarse en áreas boscosas, montañosas o sagradas donde la energía de la naturaleza es fuerte y abundante. Pueden aparecer como monturas para seres humanoides que protegen y preservan la naturaleza, actuando como guardianes de estos lugares sagrados.",
    "alineamiento": "Legal",
    "descripcion": "Los Gramenbys son criaturas de la naturaleza con cuerpos de piedra mágica y viva, cuya apariencia recuerda a los ajolotes, pero en una escala mucho más grande y robusta. Su piel de piedra está impregnada de energía mágica de la naturaleza. Poseen grandes garras metálicas afiladas y su cuerpo emana una magia que evoca símbolos mágicos tanto de la esencia de la naturaleza como la sagrada.",
    "imagen": "imgs/gramenbys.png"
  },
  {
    "nombre": "Butter Wing",
    "categoria": "Categoría 1",
    "fortalezas": "-Los ojos de Butter Wing pueden provocar alucinaciones y parálisis en aquellos que los miran directamente, sembrando el caos entre sus enemigos. Esta habilidad le permite escapar de situaciones peligrosas e incluso hacer que los enemigos se peleen o huyan entre sí.\n-Butter Wing es extremadamente hábil para esconderse y evadir el peligro. Gracias a su pequeño tamaño y su capacidad para teletransportarse, puede desaparecer rápidamente de la vista de sus perseguidores, dejando solo un charco de sangre como rastro.\n-A pesar de su falta de comunicación verbal, Butter Wing es una criatura astuta y resolutiva. Sabe cómo aprovechar su entorno y sus habilidades para sobrevivir y confundir a sus enemigos.",
    "debilidades": "-A pesar de su habilidad para infundir miedo, Butter Wing es una criatura pequeña y frágil, lo que lo hace vulnerable a los ataques físicos directos. Un golpe certero puede acabar con él rápidamente.\n-Su capacidad de teletransportación deja un charco de sangre como rastro, lo que puede revelar su posición a los enemigos perspicaces. Además, su necesidad de sangre puede limitar su capacidad de movimiento si no encuentra suficientes fuentes.\n-Butter Wing no tiene la capacidad de comunicarse con otros seres inteligentes o razas, lo que puede dificultar su capacidad para formar alianzas o recibir ayuda de otros seres inteligentes.",
    "dano_texto": "1D4 (Daño Psíquico)",
    "dano": 0,
    "ca": 17,
    "vitalidad": 8,
    "px": 360,
    "movimiento": 2,
    "dano_alcance": 4,
    "localizacion": "Originario de un plano existencial ya extinto, ahora en el plano terrenal. Reside principalmente en las islas de las Blemias, donde encuentra un entorno perfecto para su naturaleza. Son criaturas respetadas en las islas por su relación con los habitantes locales, ya que las Blemias son inmunes a sus poderes.",
    "alineamiento": "Neutral/Caótico",
    "descripcion": "Butter Wing es una criatura singular que parece ser una amalgama de diferentes especies. Tiene el cuerpo de un pequeño pingüino, pero con algunas características únicas que lo hacen destacar. Sus alas son similares a las de una mariposa, delicadas y coloridas, lo que contrasta con su aspecto general. En su cabeza, lleva una especie de aureola roja que emite un brillo misterioso, y una antena que se eleva hacia ella. Sus ojos, de un rojo carmesí intenso, tienen la capacidad de infundir alucinaciones en aquellos que los miran directamente.",
    "imagen": "imgs/butterwing.png"
  },
  {
    "nombre": "Carnifex",
    "categoria": "Categoría 1",
    "fortalezas": "-La mirada penetrante y la presencia imponente del Carnifex pueden infundir miedo en aquellos que lo enfrentan, disuadiendo posibles agresores.\n-Su capacidad para rodearse de llamas y plumas en momentos de peligro indica un control sobre los elementos del plano de ensueño, lo que le otorga una ventaja defensiva significativa.\n-El Carnifex puede percibir el aura de los seres de diferentes planos existenciales, lo que le permite identificar amenazas potenciales y reaccionar de manera adecuada.",
    "debilidades": "-No son buenos combatientes físicamente y son fácilmente espantables cuando se ven muy superados.\n-Aunque su capacidad para percibir el aura de otros seres es una ventaja, también puede ser engañado por aquellos que ocultan o manipulan su propia aura.\n-A pesar de su apariencia imponente, el Carnifex puede ser vulnerable a ataques a distancia o estrategias que aprovechen su falta de agilidad o resistencia física.",
    "dano_texto": "1D6 (Mordisco)",
    "dano": 0,
    "ca": 10,
    "vitalidad": 17,
    "px": 650,
    "movimiento": 5,
    "dano_alcance": 1,
    "localizacion": "El Carnifex se encuentra principalmente en el plano de ensueño, donde su presencia es una parte integral del ecosistema y de la dinámica de ese reino. Prefiere habitar en áreas boscosas y selváticas, donde puede utilizar su capacidad para camuflarse entre los colores con mayor eficacia.",
    "alineamiento": "Neutral",
    "descripcion": "El Carnifex es una criatura residente del plano de ensueño. Con rasgos que combinan elementos de macaco y ave, aunque no se ajusta completamente a ninguno de los dos. Su tamaño y constitución es similar al de un primate común, pero su presencia es imponente gracias a su mirada penetrante y su boca abierta, que revela una dentadura afilada. Cuando se siente amenazado, su cuerpo se rodea de llamas y plumas, aumentando su agresividad. Estas manifestaciones elementales reflejan su conexión con el plano de ensueño. Aunque está en sintonía con los seres de su propio plano, muestra una naturaleza beligerante hacia criaturas de otros planos. Puede percibir el aura de estos seres, lo que le permite reconocer amenazas de manera instintiva.",
    "imagen": "imgs/carnifex.png"
  },
  {
    "nombre": "Chupacabras",
    "categoria": "Categoría 1",
    "fortalezas": "-El Chupacabras aprovecha la oscuridad para ocultarse y realizar sus ataques sin ser detectado, siendo especialmente peligroso durante la noche.\n-Se cree que el Chupacabras tiene la habilidad de camuflarse o desaparecer rápidamente después de sus ataques, lo que dificulta su captura o detección por parte de los perseguidores.\n-Cuando ataca a sus presas, el Chupacabras puede succionar la sangre de manera rápida y eficiente, dejando marcas de perforación características en el cuello de los animales.",
    "debilidades": "-Se sugiere que el Chupacabras es sensible a la luz brillante, lo que podría utilizarse para repelerlo o ahuyentarlo, limitando su actividad durante el día.\n-Aunque prefiere operar en la oscuridad, durante el día su actividad puede ser limitada, ofreciendo oportunidades para proteger a los animales domésticos y detectar su presencia.\n-El Chupacabras tiende a operar en soledad, lo que lo hace más vulnerable a ser descubierto si es rastreado o seguido por grupos de personas determinadas a capturarlo.",
    "dano_texto": "1D12 (Mordisco Succionador de Vida)",
    "dano": 0,
    "ca": 13,
    "vitalidad": 16,
    "px": 950,
    "movimiento": 4,
    "dano_alcance": 1,
    "localizacion": "El Chupacabras se ha avistado y reportado en zonas rurales y suburbanas de diversas regiones de Terratea. Sus apariciones son más comunes en áreas donde se crían animales domésticos, como granjas y ranchos.",
    "alineamiento": "Caótico",
    "descripcion": "El Chupacabras es una criatura temida que se cree que succiona la sangre y el alma de animales domésticos en zonas rurales. Ataca especialmente por la noche y siempre busca la forma de no ser detectado. Su apariencia varía según los relatos, pero generalmente se lo describe como un ser de alrededor de un metro a un metro veinte de altura, con rasgos que combinan características de rata, murciélago y otros animales.",
    "imagen": "imgs/chupacabras.png"
  },
  {
    "nombre": "Cocollona",
    "categoria": "Categoría 1",
    "fortalezas": "-Se dice que las lágrimas de la Cocollona poseen propiedades curativas, capaces de sanar heridas y aliviar el sufrimiento de aquellos que las reciben.\n-La Cocollona muestra dolencias para inspirar compasión en sus atacantes, lo que puede hacer que sus oponentes duden en atacarla.\n-Es resistente a venenos, enfermedades o maldiciones, lo que le permite sobrevivir en condiciones adversas y resistir ciertos ataques.",
    "debilidades": "-La Cocollona carece de velocidad y agilidad, ya que su forma híbrida no le permite moverse con soltura.\n-Su fuerza física es comparable a la de un cocodrilo, lo que la hace vulnerable en combate contra enemigos más poderosos o ágiles.\n-Es especialmente vulnerable ante cualquier tipo de magia, excepto la elemental, lo que puede ser aprovechado por magos y otros usuarios de hechizos.",
    "dano_texto": "1D4 (Mordisco)",
    "dano": 0,
    "ca": 16,
    "vitalidad": 5,
    "px": 100,
    "movimiento": 4,
    "dano_alcance": 1,
    "localizacion": "En el plano terrenal, la Cocollona se encuentra generalmente en lugares abandonados cerca de riachuelos o cuerpos de agua dulce, donde puede encontrar refugio y alimentarse.",
    "alineamiento": "Neutral/Legal",
    "descripcion": "La Cocollona es el resultado de una transfiguración humana fallida, un ser híbrido que mezcla el cuerpo de un cocodrilo con las delicadas alas de mariposa. Su aspecto evoca la imagen de un cocodrilo distorsionado y desfigurado por un error en un ritual de transfiguración humana que intentaba crear un hada con el cuerpo de una clérigo. Sus ojos reflejan tristeza y desesperación, y su presencia inspira tanto lástima como compasión. Con una conciencia atormentada por su destino fallido, la Cocollona busca desesperadamente un propósito o redención, lo que afecta su juicio y su determinación.",
    "imagen": "imgs/cocollona.png"
  },
  {
    "nombre": "Aitvaras",
    "categoria": "Categoría 1",
    "fortalezas": "-El Aitvaras es capaz de influir y aprovecharse de aquellos anfitriones que tienen una voluntad débil, lo que le permite establecer su dominio sobre ellos y utilizarlos para sus propios fines.\n-Tiene la capacidad de generar riquezas de manera diaria, lo que le proporciona una fuente constante de recursos y poder para sí mismo y para sus anfitriones.\n-Puede utilizar su pico para escupir fuego, lo que le otorga una poderosa capacidad ofensiva en combate y le permite enfrentarse a sus enemigos con ferocidad.",
    "debilidades": "-Aquellos que poseen una fuerte ética moral y se niegan a beneficiarse de riquezas obtenidas de manera deshonesta representan una debilidad para el Aitvaras, ya que su influencia sobre ellos es limitada.\n-El Aitvaras puede ser físicamente débil, lo que lo hace vulnerable en combate directo contra oponentes fuertes y hábiles en el cuerpo a cuerpo.\n-Rehuye de los cazadores que intentan domesticarlo, lo que indica una aversión a ser controlado o sometido, lo que puede ser aprovechado por aquellos que buscan enfrentarlo y liberar su influencia sobre otros.",
    "dano_texto": "1D4 (Aliento de Fuego)",
    "dano": 0,
    "ca": 19,
    "vitalidad": 6,
    "px": 100,
    "movimiento": 3,
    "dano_alcance": 2,
    "localizacion": "Originario del plano terrenal, el Aitvaras se encuentra comúnmente en hogares particulares, especialmente en zonas rurales donde la tradición y las supersticiones son más arraigadas.",
    "alineamiento": "Caótico/Legal",
    "descripcion": "El Aitvaras es una criatura mítica descrita como un gallo codicioso con alas de murciélago y cola de serpiente. Esta entidad singular se instala en una casa y, por lo general, se niega a abandonarla. Aunque trae riquezas en forma de oro y grano robados, estas adquisiciones ilícitas suelen provocar infortunios a la familia anfitriona, generando problemas y desventuras. Es considerado una entidad inquietante que trae mala suerte a quienes lo albergan.",
    "imagen": "imgs/aitvaras.png"
  }, 
  {
    "nombre": "Alicornio",
    "categoria": "Categoría 1",
    "fortalezas": "-El Alicornio tiene cierta aversión hacia el género masculino, lo que se fortalece cuando lo tienen como objetivo.\n-Prefiere resolver conflictos mediante la paz y la armonía, lo que le permite calmar a otros seres con su poder y evitar confrontaciones violentas, siendo una ventaja en situaciones de conflicto.\n-Posee resistencia ante los daños sagrados, lo que le proporciona una ventaja adicional en enfrentamientos contra entidades o habilidades que utilicen poderes sagrados.",
    "debilidades": "-El género femenino puede representar una debilidad para el Alicornio en ciertos contextos o situaciones, pudiendo ser explotado por enemigos de este género.\n-Seres que poseen habilidades mágicas oscuras o maldiciones pueden perturbar su equilibrio espiritual y con la naturaleza, lo que constituye una debilidad significativa.\n-Su cuerno es una pieza codiciada por los cazadores furtivos, representando una amenaza constante para su seguridad y convirtiéndose en una debilidad potencial en enfrentamientos contra quienes ansían obtenerlo.",
    "dano_texto": "1D10 (Cuerno Perforante)",
    "dano": 0,
    "ca": 9,
    "vitalidad": 30,
    "px": 1300,
    "movimiento": 8,
    "dano_alcance": 1,
    "localizacion": "Originario del plano ensueño, el Alicornio se cree que se manifiesta en un momento de necesidad.",
    "alineamiento": "Legal",
    "descripcion": "El Alicornio es una criatura legendaria de gran belleza y gracia, descrita como un caballo majestuoso con un largo cuerno espiral que emite una luz mágica y resplandeciente. Su pelaje suele ser de colores puros y vibrantes. Una de sus características más singulares es que, en la noche más larga del año, tiene la capacidad de cambiar el sexo de la mujer que consiga montarlo, transformándola en un hombre. Este evento es extremadamente raro y misterioso, y la transformación es irreversible. Es importante mencionar que el Alicornio no puede ser montado por un ser masculino.",
    "imagen": "imgs/alicornio.png"
  },
  {
    "nombre": "Arión",
    "categoria": "Categoría 1",
    "fortalezas": "-Poseen una gran agilidad y velocidad excepcionales en vuelo, lo que les permite moverse con rapidez y precisión, siendo hábiles cazadores y evitando ataques enemigos con facilidad.\n-Tienen sentidos agudos, especialmente la vista y el oído, que les permiten detectar presas o peligros a larga distancia, aumentando su eficacia como depredadores.\n-Pueden esquivar con facilidad los proyectiles, ya sean mágicos o no, gracias a su rápida maniobrabilidad en el aire, lo que los hace difíciles de alcanzar y dañar.",
    "debilidades": "-Son vulnerables a ataques físicos directos debido a su constitución más ligera en comparación con criaturas más grandes, lo que los hace propensos a recibir daño cuando son alcanzados.\n-Sus habilidades de combate cuerpo a cuerpo pueden ser limitadas en comparación con criaturas más musculosas o equipadas con armas, lo que los deja en desventaja en enfrentamientos cercanos.\n-Dependen mucho de estar en manadas, lo que los hace menos efectivos cuando están solos y más susceptibles a tácticas que desarticulen su coordinación y unidad.",
    "dano_texto": "2D6 (Garras)",
    "dano": 0,
    "ca": 12,
    "vitalidad": 22,
    "px": 1120,
    "movimiento": 6,
    "dano_alcance": 1,
    "localizacion": "Originario de los planos de Ensueño y Terrenal, el Arión prefiere habitar en zonas templadas, donde el clima sea propicio y le haga sentir cómodo para surcar los cielos en busca de presas y aventuras.",
    "alineamiento": "Neutral",
    "descripcion": "Arión es una criatura mística con una apariencia que fusiona rasgos de un caballo con los de un cuervo. Su plumaje es de un negro profundo y reluciente, con destellos azulados o violáceos. Aunque no es difícil de encontrar, es extremadamente difícil de atrapar debido a su agilidad y destreza en los cielos. Es altamente codiciado por cazadores, jinetes lujosos y coleccionistas de mascotas o monturas exóticas.",
    "imagen": "imgs/arion.png"
  },
  {
    "nombre": "Caparoteo",
    "categoria": "Categoría 1",
    "fortalezas": "-Resistencia y longevidad proporcionadas por su corazón de tortuga, lo que lo hace capaz de resistir largos viajes y enfrentamientos prolongados.\n-Protección natural proporcionada por sus escamas de reptil, que lo hacen difícil de herir en combate.\n-Devoción hacia su amo, lo que lo convierte en un compañero leal y dispuesto a protegerlo a toda costa.\n-Velocidad sorprendente comparable a la de un conejo, lo que lo hace una montura rápida.",
    "debilidades": "-Poca sociabilidad, ya que tiende a ser reservado y distante con los extraños, lo que puede dificultar su interacción con otros individuos.\n-Tamaño adecuado solo para personas que midan menos de 1.25 metros, lo que limita su uso como montura para personas de mayor estatura.\n-Necesidad de una alimentación abundante, especialmente frutas del bosque, para mantener su fuerte constitución.",
    "dano_texto": "1D4 (Mordisco)",
    "dano": 0,
    "ca": 6,
    "vitalidad": 10,
    "px": 470,
    "movimiento": 6,
    "dano_alcance": 1,
    "localizacion": "En el plano terrenal, los Caparoteos pueden encontrarse en entornos naturales donde puedan camuflarse entre la vegetación y aprovechar su velocidad para moverse con facilidad. Son más comunes en regiones con clima templado y abundante vegetación.",
    "alineamiento": "Neutral/Legal",
    "descripcion": "El Caparoteo es una criatura única que combina características de diferentes animales en su apariencia. Tiene escamas de reptil que recubren su cuerpo, otorgándole protección natural. Su corazón es similar al de una tortuga, lo que le confiere gran resistencia y longevidad. Sus orejas, largas y puntiagudas como las de un conejo, le permiten una audición notable y una percepción del entorno muy desarrollada. A pesar de su constitución robusta, posee una velocidad sorprendente comparable a la de un conejo, convirtiéndolo en una montura rápida y resistente.",
    "imagen": "imgs/caparoteo.png"
  },
  {
    "nombre": "Yeti",
    "categoria": "Categoría 2",
    "fortalezas": "-Su grueso pelaje lo protege del clima extremo y las bajas temperaturas de las regiones montañosas donde habita.\n-A pesar de su gran tamaño, el Yeti es ágil y fuerte, lo que le permite moverse con facilidad por terrenos difíciles y cazar presas.\n-Se cree que el Yeti es un experto en el arte del sigilo, lo que le permite evadir la detección y moverse sin ser visto en su entorno montañoso.",
    "debilidades": "-Su hábitat natural se encuentra en regiones remotas y de difícil acceso, lo que limita su interacción con los humanos y su capacidad para ser estudiado de cerca.\n-Aunque resistente, el Yeti puede ser vulnerable a la magia infernal y a los ataques de fuego, que pueden representar una amenaza para su supervivencia.\n-Se sabe que el Yeti muestra una aversión o temor hacia las tecnologías modernas, lo que podría ser explotado como una debilidad en encuentros con humanos que poseen dispositivos tecnológicos.",
    "dano_texto": "2D8 (Golpe)",
    "dano": 0,
    "ca": 13,
    "vitalidad": 75,
    "px": 9000,
    "movimiento": 6,
    "dano_alcance": 2,
    "localizacion": "En el plano terrenal, se cree que el Yeti habita en las regiones montañosas y heladas del mundo de Terratea.",
    "alineamiento": "Neutral",
    "descripcion": "El Yeti es una criatura grande y peluda, similar a un simio o un hombre primitivo, que se cree habita en las regiones remotas y nevadas. Se le describe como un ser bípedo, con una altura que puede alcanzar varios metros. Su cuerpo está cubierto de un denso pelaje, generalmente de color blanco o gris, que le proporciona protección contra el frío extremo de su hábitat. Sus características físicas incluyen una cabeza grande y redonda, con ojos profundos y oscuros, y brazos largos que le permiten moverse con facilidad a través de terrenos montañosos y nevados. A menudo se le atribuyen cualidades misteriosas y sobrenaturales.",
    "imagen": "imgs/yeti.png"
  },
  {
    "nombre": "Xiezhi",
    "categoria": "Categoría 2",
    "fortalezas": "-El Xiezhi puede detectar la bondad y la malicia con una precisión sobrenatural a través del olfato, lo que le permite juzgar a las personas de manera imparcial.\n-Su cuerpo de bronce le otorga una gran resistencia y durabilidad, lo que lo hace difícil de derribar en combate.\n-Sus dientes pueden desgarrar cualquier tipo de material, empezando siempre por los pies de su oponente, lo que le otorga un ataque poderoso en combate cuerpo a cuerpo.",
    "debilidades": "-Es susceptible a las magias elementales, lo que puede ser aprovechado por los hechiceros enemigos para debilitarlo.\n-Los golpes contundentes pueden afectarle al interior de la criatura que no está hecha del mismo material que la capa exterior, causándole daño.\n-Los olores muy fuertes pueden molestar al Xiezhi y distraerlo durante el combate, reduciendo su efectividad.",
    "dano_texto": "2D6 + 1D8 (Mordisco + golpe de cuerno)",
    "dano": 0,
    "ca": 7,
    "vitalidad": 31,
    "px": 5550,
    "movimiento": 5,
    "dano_alcance": 1,
    "localizacion": "En el plano terrenal, el Xiezhi reside principalmente en la capital Wuzetang del reino del este, donde actúa como juez y ejecutor de la moralidad. Se le puede encontrar cerca de los samuráis imperiales que protegen el reino.",
    "alineamiento": "Neutral/Legal",
    "descripcion": "El Xiezhi es una criatura peculiar que habita en la capital Wuzetang del reino del este. Se le conoce por su capacidad sobrenatural para detectar la maldad y la bondad en las personas a través del olfato. Su cuerpo está hecho de bronce, otorgándole una apariencia metálica. Posee una campana que utiliza como instrumento de juicio: suena cuando percibe la bondad en una persona y ataca si detecta malicia. Los ojos del Xiezhi son de un rojo oscuro, profundos y penetrantes. Además, cuenta con dos cuernos superiores, bigotes, cuerpo de animal de aproximadamente 2 metros y una complexión musculada similar a la de un gran felino, con cara de perro y pelaje en el cuello; además ostenta pinchos en su espalda.",
    "imagen": "imgs/xiezhi.png"
  },
  {
    "nombre": "Wulwolen",
    "categoria": "Categoría 2",
    "fortalezas": "-Posee una visión excepcional que le permite cazar incluso en las condiciones más oscuras del fondo del mar, lo que lo hace un cazador eficiente en entornos de baja visibilidad.\n-Sus mandíbulas son extremadamente corrosivas, descomponiendo la carne de sus presas rápidamente y facilitando su digestión.\n-Una vez que ha probado la carne de una presa, puede rastrearla sin cesar, viendo su ubicación en todo momento y sin detenerse hasta capturarla o morir.",
    "debilidades": "-No puede corroer el metal del plano elemental ni la roca de mar, limitando su efectividad contra ciertas defensas.\n-La dependencia de la carne para adquirir la capacidad de rastreo puede limitar su capacidad de caza en entornos donde la comida escasea.\n-El trance de caza en el que entra puede hacerlo ignorar su propia seguridad y necesidades básicas, poniéndose en situaciones peligrosas.",
    "dano_texto": "1D6 + 1D4 (Mandíbulas corrosivas)",
    "dano": 0,
    "ca": 14,
    "vitalidad": 38,
    "px": 1550,
    "movimiento": 6,
    "dano_alcance": 1,
    "localizacion": "En el plano terrenal, en sitios donde halla agua.",
    "alineamiento": "Caótico",
    "descripcion": "El Wulwolen es una criatura depredadora del plano elemental, de poco más que un metro de altura, con unos ojos que pueden ver en las zonas más oscuras del fondo del mar. Habita en áreas con presencia de agua dulce y destaca por sus mandíbulas corrosivas, capaces de descomponer rápidamente la carne de sus presas. Una vez que prueba la carne de una presa, puede rastrearla en todo momento, sin cesar en su caza hasta capturarla o morir en el intento, ya que entra en un trance imparable durante la caza que no puede evitar.",
    "imagen": "imgs/wulwolen.png"
  },
  {
    "nombre": "Urco",
    "categoria": "Categoría 2",
    "fortalezas": "-El aullido del Urco puede dejar paralizado de miedo a quien lo escuche, inmovilizándolo y facilitando su ataque.\n-El Urco puede devorar cualquier ser vivo con una ferocidad y rapidez asombrosas, despedazando cuerpos y consumiendo sus restos sin dejar rastro; esta habilidad le permite recuperar vitalidad a partir de sus víctimas, manteniéndose en un estado de constante fuerza y energía.\n-El Urco arrastra cadenas que puede usar como armas, golpeando a sus enemigos con una fuerza devastadora.",
    "debilidades": "-Aunque puede usarlas como armas, las cadenas también pueden ser su debilidad si se utilizan adecuadamente contra él.\n-Su aparición está restringida a una vez al mes, lo que permite a las personas prepararse para su llegada o incluso evitarlo por completo si son conscientes de su horario.\n-Son vulnerables al control mental hacia los animales, lo que podría ser aprovechado por aquellos con habilidades de manipulación mental.",
    "dano_texto": "2D6 + 1D8 (Mordisco + golpe de cadenas)",
    "dano": 0,
    "ca": 9,
    "vitalidad": 84,
    "px": 15650,
    "movimiento": 6,
    "dano_alcance": 3,
    "localizacion": "En el plano terrenal, el Urco suele aparecer emergiendo del mar durante la noche, devorando a sus presas en tierra firme antes de regresar al agua antes del alba. Su presencia se ha registrado en áreas costeras y cerca de cuerpos de agua.",
    "alineamiento": "Neutral/Caótico",
    "descripcion": "El Urco es una criatura temible que se asemeja a un perro oscuro con cuernos de cabra. Suele aparecer encadenado emergiendo de los mares, arrastrando sus cadenas con un estruendo que se puede escuchar a gran distancia. Esta bestia es de gran tamaño y emite un aullido agudo y escalofriante que infunde terror en quienes lo escuchan. Se le describe devorando a cualquier ser vivo que encuentre, despedazando los cuerpos y dejando los huesos masticados a su paso. Después de su festín, regresa al mar antes del alba.",
    "imagen": "imgs/urco.png"
  },
  {
    "nombre": "Veronte",
    "categoria": "Categoría 2",
    "fortalezas": "-El Veronte posee una gran resistencia y fuerza física, lo que le permite resistir ataques y causar daño considerable en el combate cuerpo a cuerpo.\n-Sus grandes colmillos y cuernos son armas naturales poderosas que pueden infligir daño significativo a sus oponentes.\n-Los agujeros en la piel del Veronte le permiten liberar gases tóxicos, que pueden ser utilizados como una táctica defensiva o para debilitar a sus enemigos en combate.",
    "debilidades": "-A pesar de su constitución física robusta, el Veronte puede ser vulnerable a ataques a distancia que le impidan acercarse lo suficiente a sus oponentes.\n-Si el Veronte no puede controlar adecuadamente la liberación de sus gases tóxicos, puede verse afectado negativamente por ellos, poniendo en peligro su propia salud.\n-Se cree que el gas es altamente inflamable, lo que podría representar un riesgo tanto para el Veronte como para sus alrededores.",
    "dano_texto": "1D12 (Cornada)",
    "dano": 0,
    "ca": 10,
    "vitalidad": 111,
    "px": 5800,
    "movimiento": 6,
    "dano_alcance": 2,
    "localizacion": "En el plano terrenal, el Veronte puede encontrarse en áreas remotas y áridas, pero donde haya algo de vegetación que le permita camuflarse y emboscar a sus presas.",
    "alineamiento": "Neutral/Caótico",
    "descripcion": "El Veronte es una criatura imponente y resistente, similar a un rinoceronte en su apariencia física, pero con algunas características distintivas que lo hacen destacar. Posee una constitución física masiva y robusta, lo que le otorga una gran fuerza y aguante en el combate. Sus colmillos, grandes y afilados, sobresalen de su mandíbula, añadiendo una peligrosa arma adicional además de su gran cuerno. Sin embargo, lo más notable son los múltiples agujeros dispersos por su piel, los cuales son utilizados por el Veronte para expulsar gases tóxicos cuando así lo desea. Se cree que estas características únicas son el resultado de una maldición proveniente del plano abisal.",
    "imagen": "imgs/veronte.png"
  },
  {
    "nombre": "Transmutación Fallida",
    "categoria": "Categoría 2",
    "fortalezas": "-La imprevisibilidad de su forma y comportamiento puede desconcertar y desorientar a los oponentes, dificultando la planificación de ataques en su contra.\n-La combinación aleatoria de partes animales y mágicas puede otorgarles habilidades inesperadas y sorprendentes en combate.\n-Su breve existencia les permite desatar ráfagas intensas de energía mágica temporal antes de desmoronarse o desaparecer, lo que les hace peligrosos en encuentros a corto plazo.",
    "debilidades": "-Son inherentemente inestables y propensos a desmoronarse o desaparecer en cualquier momento, lo que los hace poco fiables en combates prolongados.\n-Son extremadamente vulnerables a cualquier tipo de daño arcano o infernal, que puede acelerar su desintegración.\n-Se rigen principalmente por sus instintos animales, lo que los hace predecibles hasta cierto punto, pues sus acciones suelen ser impulsivas y basadas en reacciones instintivas en lugar de estrategias conscientes.",
    "dano_texto": "1D4 + 1D6 + 1D8 + 1D10 + 1D12 (Ráfaga de daño mágico)",
    "dano": 0,
    "ca": 11,
    "vitalidad": 32,
    "px": 39400,
    "movimiento": 7,
    "dano_alcance": 3,
    "localizacion": "En el plano terrenal o arcano, las transmutaciones fallidas pueden encontrarse en los laboratorios de alquimia de alquimistas novatos o imprudentes. También pueden aparecer en áreas donde la magia ha sido mal utilizada o distorsionada, creando condiciones propicias para la manifestación de criaturas caóticas.",
    "alineamiento": "Caótico",
    "descripcion": "Una transmutación fallida es el resultado de un intento de un alquimista novato o imprudente de realizar una transformación animal sin la habilidad o el conocimiento adecuado. Este proceso produce una almágana inestable, una criatura caótica y aberrante. Estas criaturas son combinaciones de diferentes partes de animales, mezcladas de manera desordenada y grotesca. Su forma es distorsionada y poco natural, con una apariencia que causa repulsión y temor. Las transmutaciones fallidas son inestables y peligrosas, y su existencia suele ser breve debido a su naturaleza desequilibrada.",
    "imagen": "imgs/transmutacionfallida.png"
  },
  {
    "nombre": "Salamandra",
    "categoria": "Categoría 2",
    "fortalezas": "-Las salamandras pueden soportar altas temperaturas y entornos ígneos sin sufrir daños. Son inmunes a las quemaduras y al daño por fuego elemental.\n-Se les atribuye la capacidad de controlar el fuego, lo que les otorga una ventaja en el combate y en la manipulación de su entorno.\n-Las salamandras son habilidosas en el uso de armas y escudos, lo que las convierte en oponentes formidables en la batalla.",
    "debilidades": "-A pesar de su afinidad con el fuego, las salamandras suelen ser vulnerables al agua, que puede apagar su poder y debilitarlas.\n-Su supervivencia puede depender en gran medida de la presencia de fuego en su entorno, lo que las hace vulnerables en lugares donde no hay fuego disponible.\n-Algunas representaciones de las salamandras las muestran como criaturas temperamentales y propensas a la ira, lo que puede llevarlas a actuar de manera impulsiva o imprudente.",
    "dano_texto": "3D6 (Lanza ígnea)",
    "dano": 0,
    "ca": 7,
    "vitalidad": 30,
    "px": 12800,
    "movimiento": 5,
    "dano_alcance": 2,
    "localizacion": "En el plano terrenal, las salamandras son más comunes en zonas muy calientes, como volcanes, cuevas volcánicas o regiones subterráneas donde el calor es intenso.",
    "alineamiento": "Neutral",
    "descripcion": "Las salamandras son criaturas asociadas con el elemento del fuego, a menudo representadas como lagartijas o serpientes de fuego con torsos humanoides y cabezas draconianas. Poseen la notable capacidad de resistir altas temperaturas e incluso de controlar el fuego a su alrededor. Su aspecto y comportamiento pueden variar ampliamente, desde seres benevolentes que ayudan a los humanos hasta criaturas feroces que causan estragos. Algunas salamandras son hábiles en el uso de armas y escudos, lo que las hace aún más formidables en combate.",
    "imagen": "imgs/salamandra.png"
  },
  {
    "nombre": "Quimera",
    "categoria": "Categoría 2",
    "fortalezas": "-La quimera tiene la capacidad de expulsar fuego por la boca, lo que le otorga un poderoso ataque a distancia.\n-Puede moldear su cuerpo para adaptarse a diferentes situaciones, volviéndolo más delgado como el de una serpiente o más musculoso como el de un león, según sus necesidades.\n-Tiene una alta resistencia a los efectos de la magia arcana, lo que le permite resistir hechizos y ataques mágicos con relativa facilidad.",
    "debilidades": "-A pesar de su apariencia imponente, la quimera es herbívora, lo que la hace vulnerable a los ataques de depredadores mayores que pueden verla como una presa.\n-Tiende a ser desconfiada, lo que puede dificultar las interacciones pacíficas con otras criaturas, incluidas las de su propia especie.\n-Es vulnerable a las magias infernales y a las maldiciones, que pueden debilitar su resistencia y ponerla en peligro.",
    "dano_texto": "4D8 (Garras)",
    "dano": 0,
    "ca": 7,
    "vitalidad": 80,
    "px": 7750,
    "movimiento": 6,
    "dano_alcance": 2,
    "localizacion": "En el plano terrenal, la quimera puede encontrarse en diversas regiones de Terratea, especialmente en áreas salvajes y remotas como bosques densos, montañas escarpadas o cavernas profundas.",
    "alineamiento": "Neutral/Caótico",
    "descripcion": "La quimera es una criatura mítica que ha sido descrita de varias maneras a lo largo de la historia de Terratea. Comúnmente se la representa como un ser híbrido con la cabeza y cuerpo de un león, cuernos de una cabra y la cola serpenteante. Su apariencia es feroz y única. Se cree que la quimera es posiblemente la primera de las creaciones en la historia de Terratea realizadas mediante habilidades de transmutación animal, y que con el paso de los milenios se ha quedado como parte de la fauna del mundo.",
    "imagen": "imgs/quimera.png"
  }
];

try {
  localStorage.setItem('bestias', JSON.stringify(window.bestias));
} catch (_) {}
